/**
 * \file Ifx_reg.h
 * \brief
 * \copyright Copyright (c) 2012 Infineon Technologies AG. All rights reserved.
 *
 * Version: TC27XD_UM_V2.2.R1
 * Specification: Refer to module specific file heading
 * MAY BE CHANGED BY USER [yes/no]: No
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef IFX_REG_H
#define IFX_REG_H 1

#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxAsclin_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxCan_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxCbs_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxCcu6_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxCif_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxCpu_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxDma_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxDsadc_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxEbcu_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxEmem_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxEray_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxEth_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxFce_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxFlash_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxGpt12_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxGtm_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxHsct_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxHssl_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxI2c_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxInt_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxIom_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxLmu_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxMc_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxMsc_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxMtu_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxOvc_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxPmu_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxPort_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxPsi5_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxPsi5s_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxQspi_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxSbcu_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxScu_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxSent_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxSmu_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxSrc_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxStm_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxVadc_reg.h"
#include "../../../../../Common_Drivers/Infra/Sfr/TC27D/_Reg/IfxXbar_reg.h"

#endif /*IFX_REG_H*/

