/********************************************************************************************************************
 * \file MULTICAN.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "CAN_Mgr.h"
#include "CAN_Unit.h"


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
AppMulticanType   g_multican;                               /* Global MULTICAN configuration and control structure   */
/* Define the content of the data to be transmitted */
uint16 CAN_MESSAGE_ID = 0x00;
uint32 BcmDataLow;
uint32 BcmDataHigh;
uint32 Dcu01DataLow;
uint32 Dcu01DataHigh;
uint32 Dcu02DataLow;
uint32 Dcu02DataHigh;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Macro to define Interrupt Service Routine.
 * This macro:
 * - defines linker section as .intvec_tc<vector number>_<interrupt priority>.
 * - defines compiler specific attribute for the interrupt functions.
 * - defines the Interrupt service routine as ISR function.
 *
 * IFX_INTERRUPT(isr, vectabNum, priority)
 *  - isr: Name of the ISR function.
 *  - vectabNum: Vector table number.
 *  - priority: Interrupt priority. Refer Usage of Interrupt Macro for more details.
 */
IFX_INTERRUPT(canIsrRxHandler, 0, ISR_PRIORITY_CAN_RX);



/* Interrupt Service Routine (ISR) called once the RX interrupt has been generated.
 * Compares the content of the received CAN message with the content of the transmitted CAN message
 * and in case of success, turns on the LED2 to indicate successful CAN message reception.
 */
void canIsrRxHandler(void)
{
    IfxMultican_Status readStatus;

    /* Read the received CAN message and store the status of the operation */
    readStatus = IfxMultican_Can_MsgObj_readMessage(&g_multican.canRxMsgObj, &g_multican.rxMsg);


    /* Turn on the LED2 to indicate correctness of the received message */
    if (g_multican.rxMsg.id == 0x52)
    {
        BcmDataLow = g_multican.rxMsg.data[0];
        BcmDataHigh = g_multican.rxMsg.data[1];
    }
    else if (g_multican.rxMsg.id == 0x88)
    {
        Dcu01DataLow = g_multican.rxMsg.data[0];
        Dcu01DataHigh = g_multican.rxMsg.data[1];
    }
    else if (g_multican.rxMsg.id == 0x89)
    {
        Dcu02DataLow = g_multican.rxMsg.data[0];
        Dcu02DataHigh = g_multican.rxMsg.data[1];
    }
}

uint32 getBcmDataLow(void)
{
    return BcmDataLow;
}
uint32 getBcmDataHigh(void)
{
    return BcmDataHigh;
}
uint32 getDcu01DataLow(void)
{
    return Dcu01DataLow;
}
uint32 getDcu01DataHigh(void)
{
    return Dcu01DataHigh;
}
uint32 getDcu02DataLow(void)
{
    return Dcu02DataLow;
}
uint32 getDcu02DataHigh(void)
{
    return Dcu02DataHigh;
}

/* Function to initialize MULTICAN module, nodes and message objects related for this application use case */
void initMultican(void)
{
    /* ==========================================================================================
     * CAN module configuration and initialization:
     * ==========================================================================================
     *  - load default CAN module configuration into configuration structure
     *
     *  - define the interrupt priority for both interrupt node pointers used in the example
     *
     *  - initialize CAN module with the modified configuration
     * ==========================================================================================
     */
    IfxMultican_Can_initModuleConfig(&g_multican.canConfig, &MODULE_CAN);
    g_multican.canConfig.nodePointer[RX_INTERRUPT_SRC_ID].priority = ISR_PRIORITY_CAN_RX;

    IfxMultican_Can_initModule(&g_multican.can, &g_multican.canConfig);

    /* ==========================================================================================
     * Source CAN node configuration and initialization:
     * ==========================================================================================
     *  - load default CAN node configuration into configuration structure
     *
     *  - set source CAN node in the "Loop-Back" mode (no external pins will be used)
     *  - assign source CAN node to CAN node 0
     *
     *  - initialize the source CAN node with the modified configuration
     * ==========================================================================================
     */
    IfxMultican_Can_Node_initConfig(&g_multican.canNodeConfig, &g_multican.can);

    g_multican.canNodeConfig.txPin  = &IfxMultican_TXD0_P20_8_OUT;
    g_multican.canNodeConfig.rxPin  = &IfxMultican_RXD0B_P20_7_IN;
    g_multican.canNodeConfig.nodeId = IfxMultican_NodeId_0;

    IfxMultican_Can_Node_init(&g_multican.canNode, &g_multican.canNodeConfig);

    /* ==========================================================================================
     * Source message object configuration and initialization:
     * ==========================================================================================
     *  - load default CAN message object configuration into configuration structure
     *
     *  - define the message object ID
     *  - define the CAN message ID used during arbitration phase
     *  - define the message object as a transmit message object
     *  - enable interrupt generation in case of CAN message transmission
     *  - define interrupt node pointer to be used
     *
     *  - initialize the source CAN message object with the modified configuration
     * ==========================================================================================
     */
    IfxMultican_Can_MsgObj_initConfig(&g_multican.canMsgObjConfig, &g_multican.canNode);

    g_multican.canMsgObjConfig.msgObjId             = TX_MESSAGE_OBJECT_ID;
    g_multican.canMsgObjConfig.frame                = IfxMultican_Frame_transmit;

    IfxMultican_Can_MsgObj_init(&g_multican.canTxMsgObj, &g_multican.canMsgObjConfig);

    /* ==========================================================================================
     * Destination message object configuration and initialization:
     * ==========================================================================================
     *  - load default CAN message object configuration into configuration structure
     *
     *  - define the message object ID (different than the ID used for source MO)
     *  - define the CAN message ID used during arbitration phase (same as ID used for source MO)
     *  - define the message object as a receive message object
     *  - enable interrupt generation in case of CAN message transmission
     *  - define interrupt node pointer to be used (different than the one used for source MO)
     *
     *  - initialize the destination CAN message object with the modified configuration
     * ==========================================================================================
     */
    IfxMultican_Can_MsgObj_initConfig(&g_multican.canMsgObjConfig, &g_multican.canNode);

    g_multican.canMsgObjConfig.msgObjId             = RX_MESSAGE_OBJECT_ID;
    //g_multican.canMsgObjConfig.messageId          = CAN_MESSAGE_ID;
    g_multican.canMsgObjConfig.acceptanceMask       = 0UL;
    g_multican.canMsgObjConfig.frame                = IfxMultican_Frame_receive;
    g_multican.canMsgObjConfig.rxInterrupt.enabled  = TRUE;
    g_multican.canMsgObjConfig.rxInterrupt.srcId    = RX_INTERRUPT_SRC_ID;

    IfxMultican_Can_MsgObj_init(&g_multican.canRxMsgObj, &g_multican.canMsgObjConfig);
}

/* Function to initialize both TX and RX messages with the default data values.
 * After initialization of the messages, the TX message will be transmitted.
 */
void transmitCanMessage(FrameIdentify idTransmit,uint32 dataLow,uint32 dataHigh)
{
    if (idTransmit == DCU_1)
    {
        CAN_MESSAGE_ID = 0x88;
    }
    else if (idTransmit == DCU_2)
    {
        CAN_MESSAGE_ID = 0x89;
    }
    else if (idTransmit == DCU_3)
    {
        CAN_MESSAGE_ID = 0x90;
    }
    else if (idTransmit == DCU_4)
    {
        CAN_MESSAGE_ID = 0x91;
    }

    /* Invalidation of the RX message */
    //IfxMultican_Message_init(&g_multican.rxMsg, 0, 0, 0, g_multican.canMsgObjConfig.control.messageLen);

    /* Initialization of the TX message */
    IfxMultican_Message_init(&g_multican.txMsg, CAN_MESSAGE_ID, dataLow, dataHigh, g_multican.canMsgObjConfig.control.messageLen);

    while( IfxMultican_Status_notSentBusy == IfxMultican_Can_MsgObj_sendMessage(&g_multican.canTxMsgObj, &g_multican.txMsg) )
    {
    }
}

