/********************************************************************************************************************
 * \file MULTICAN.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "CAN_Unit.h"
#include "CAN_Mgr.h"
#include "Data_Transfer.h"

uint32 frameHigh;
uint32 frameLow;
uint8 i=0;
uint8 dcuCounter[2] = {0,0};
uint8 dcu01FrameLow[4] = {8,24,26,25};
uint8 dcu01FrameHigh[4] = {1,0,32,33};
uint8 dcu02FrameLow[4] = {32,33,26,25};
uint8 dcu02FrameHigh[4] = {1,0,40,40};
uint8 dcu03FrameLow[4] = {40,33,26,25};
uint8 dcu03FrameHigh[4] = {1,0,40,40};
uint8 dcu04FrameLow[4] = {40,33,26,25};
uint8 dcu04FrameHigh[4] = {1,0,40,40};

uint8 frameStep[4] = {24,16,8,0};
uint32 CanBcmDataLow;
uint32 CanBcmDataHigh;
uint32 CanDcu01DataLow;
uint32 CanDcu01DataHigh;
uint32 CanDcu02DataLow;
uint32 CanDcu02DataHigh;


void sendFrame(FrameIdentify FrameId)
{
    frameHigh = 0x00;
    frameLow = 0x00;
    dcuCounter[0] = dcuCounter[0] + 1;
    if(dcuCounter[0]>254)
    {
        dcuCounter[0] = 0;
    }
    if (FrameId == DCU_1)
    {
        for (i = 0; i < 4; i++)
        {
            frameLow = frameLow | FSM_Data_DCU.dataVector[dcu01FrameLow[i]] << frameStep[i];
            if (i < 2)
            {
                frameHigh = frameHigh | dcuCounter[dcu01FrameHigh[i]] << frameStep[i];
            }
            else
            {
                frameHigh = frameHigh | FSM_Data_DCU.dataVector[dcu01FrameHigh[i]] << frameStep[i];
            }
        }
    }
    else if (FrameId == DCU_2)
    {
        dcuCounter[0] = dcuCounter[0] + 1;
        for (i = 0; i < 4; i++)
        {
            frameLow = frameLow | FSM_Data_DCU.dataVector[dcu02FrameLow[i]] << frameStep[i];
            if (i < 2)
            {
                frameHigh = frameHigh | dcuCounter[dcu02FrameHigh[i]] << frameStep[i];
            }
            else
            {
                frameHigh = frameHigh | FSM_Data_DCU.dataVector[dcu02FrameHigh[i]] << frameStep[i];
            }
        }
    }
    else if (FrameId == DCU_3)
    {
        dcuCounter[0] = dcuCounter[0] + 1;
        for (i = 0; i < 4; i++)
        {
            frameLow = frameLow | FSM_Data_DCU.dataVector[dcu03FrameLow[i]] << frameStep[i];
            if (i < 2)
            {
                frameHigh = frameHigh | dcuCounter[dcu03FrameHigh[i]] << frameStep[i];
            }
            else
            {
                frameHigh = frameHigh | FSM_Data_DCU.dataVector[dcu03FrameHigh[i]] << frameStep[i];
            }
        }
    }
    else if (FrameId == DCU_4)
    {
        dcuCounter[0] = dcuCounter[0] + 1;
        for (i = 0; i < 4; i++)
        {
            frameLow = frameLow | FSM_Data_DCU.dataVector[dcu04FrameLow[i]] << frameStep[i];
            if (i < 2)
            {
                frameHigh = frameHigh | dcuCounter[dcu04FrameHigh[i]] << frameStep[i];
            }
            else
            {
                frameHigh = frameHigh | FSM_Data_DCU.dataVector[dcu04FrameHigh[i]] << frameStep[i];
            }
        }
    }
    transmitCanMessage(FrameId, frameLow, frameHigh);
}
void readFrames()
{
    CanBcmDataLow = getBcmDataLow();
    FSM_Data_DCU.dataVector[30] = CanBcmDataLow >>16;

    CanDcu01DataLow = getDcu01DataLow();
    CanDcu01DataHigh = getDcu01DataHigh();

    FSM_Data_DCU.dataVector[23] = (uint8)(CanDcu01DataLow >> 16);
    FSM_Data_DCU.dataVector[29] = (uint8)(CanDcu01DataLow >> 24);
    FSM_Data_DCU.dataVector[36] = (uint8)(CanDcu01DataHigh >> 8); //Y1

    CanDcu02DataLow = getDcu02DataLow();
    CanDcu02DataHigh = getDcu02DataHigh();
    FSM_Data_DCU.dataVector[37] = (uint8)(CanDcu02DataLow>>24);  //Y2
}

